apiVersion: v2
name: appchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 0.0.0

dependencies:
  - name: common
    repository: oci://ghcr.io/riftonix/helm-shared/charts
    version: 2.x.x
